name: CI Linux

on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "release", "workflow_dispatch", "schedule"]'

  build-windows:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release]
        arch: [x64]
    name: 'Linux [${{ matrix.arch }}, ${{ matrix.configuration }}]'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install libs
      run: |
        sudo apt-get update && sudo apt-get install libsdl2-dev libopenal-dev libvorbis-dev libglu1-mesa-dev libgl-dev libcg libcggl
    - name: Configure and build
      run: |
        mkdir build && cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -DCG_LIB_PATH=/usr/lib/x86_64-linux-gnu
        ninja
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: farcry.${{ matrix.arch }}-${{ matrix.configuration }}
        path: bin/${{ matrix.arch }}-${{ matrix.configuration }}

permissions: write-all
